steps:
  deploy-homolog:
    image: docker:latest
    when:
      branch: homolog
      event: 
        - push
        - pull_request
    commands:
      - cd /home/univates/project/task-2-gcs
      - git pull origin homolog
      - docker-compose -f docker-compose.homolog.yml -p homolog up -d --build

  deploy-prod:
    image: docker:latest
    when:
      branch: main
      event: 
        - push
        - pull_request    
    commands:
      - cd /home/univates/project/task-2-gcs
      - git pull origin main
      - docker-compose -f docker-compose.prod.yml -p prod up -d --build
