services:
  backend:
    container_name: backend-homolog
    build: ./backend
    ports:
      - "3001:3000"
    depends_on:
      - db
    env_file:
      - backend/.env.homolog
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=banco_gcs
      - DB_PORT=5432
    restart: unless-stopped

  db:
    container_name: db-homolog
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres 
      - POSTGRES_DB=banco_gcs
    ports:
      - "5435:5432"
    volumes:
      - ./data-homolog:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    restart: unless-stopped

  frontend:
    container_name: frontend-homolog
    build: ./frontend-novo
    ports:
      - "5174:80"
    restart: unless-stopped

  frontend-test:
    profiles: ["test"] 
    build:
      context: ./frontend-novo
      target: builder
    working_dir: /app
    command: sh -c "npm install && npx vitest run"
    volumes:
      - ./frontend-novo:/app
