services:
  backend:
    container_name: backend-dev
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - backend/.env
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=banco_gcs
      - DB_PORT=5432
    restart: unless-stopped

  db:
    container_name: db-dev
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres 
      - POSTGRES_DB=banco_gcs
    ports:
      - "5434:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    restart: unless-stopped

  frontend:
    container_name: frontend-dev
    build: ./frontend-novo
    ports:
      - "5173:80"
    restart: unless-stopped

volumes:
  pgdata: